### PR TITLE
Loderunner API MI Implementation

### PR DESCRIPTION
**Pull request by TravisFallsMSFT**
# Type of PR

- [x] Documentation changes
- [x] Code changes
- [x] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## PR Checklist

- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] My code follows the code style of this project.
- [x] I ran lint checks locally prior to submission.
- [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Purpose of PR
This PR implements the Managed Identity authentication scheme for loderunner.  This will implement the ability to authenticate to Cosmos via secret keys or managed identity. 

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Issues Closed or Referenced

- Closes #1051

### CODE REVIEW

**Review by gortegaMS — CHANGES_REQUESTED** [review]
Also, VS2022 displays a couple of these Warnings, I think is a good idea to get them fixed
Warning: The .NET SDK has newer analyzers with version '7.0.0' than what version '6.0.0' of 'Microsoft.CodeAnalysis.NetAnalyzers' package provides. Update or remove this package

**Comment by TravisFallsMSFT** [comment]
> Also, VS2022 displays a couple of these Warnings, I think is a good idea to get them fixed Warning: The .NET SDK has newer analyzers with version '7.0.0' than what version '6.0.0' of 'Microsoft.CodeAnalysis.NetAnalyzers' package provides. Update or remove this package

@gortegaMS when trying to add 7 it says it isn't in production state.  Do you want me to add this one? 
info : Adding PackageReference for package 'Microsoft.CodeAnalysis.NetAnalyzers' into project info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.netanalyzers/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.codeanalysis.netanalyzers/index.json 330ms
error: NU1102: Unable to find package Microsoft.CodeAnalysis.NetAnalyzers with version (>= 7.0.0)
error:   - Found 18 version(s) in nuget.org [ Nearest version: 7.0.0-preview1.22518.1 ]
error:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
error:   - Found 0 version(s) in C:\Program Files\dotnet\library-packs
error: Package 'Microsoft.CodeAnalysis.NetAnalyzers' is incompatible with 'all' frameworks in project

**Comment by TravisFallsMSFT** [comment]
> it says it isn't in production state. Do you want me to add this one?
> info : Adding PackageReference for package 'Microsoft.CodeAnalysis.NetAnalyzers' into project inf

I figured out how to do this; it is on 7 now.

**Comment by TravisFallsMSFT** [comment]
> 

Analyzers upgraded to 7 from 6 
No warnings on compile.

**Pull request merged**
